Models/Course.cs
using System;
using System.Collections.Generic;

namespace University.Models
{
  public class Course
  {
    public Course()
    {
      this.Students = new HashSet<CourseStudent>();
    }

    public int CourseId { get; set; }
    public string Title { get; set; }
    public int Number { get; set; }
    public ICollection<CourseStudent> Students { get; }

  }
}

Models/CourseStudent.cs
namespace University.Models
{
  public class CourseStudent
  {
    public int CourseStudentId { get; set; }
    public int CourseId { get; set; }
    public int StudentId { get; set; }
    public Course Course { get; set; }
    public Student Student { get; set; }

  }
}

Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace University.Models
{
  public class UniversityContextFactory : IDesignTimeDbContextFactory<UniversityContext>
  {

    UniversityContext IDesignTimeDbContextFactory<UniversityContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<UniversityContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new UniversityContext(builder.Options);
    }
  }
}

Models/Student.cs
using System;
using System.Collections.Generic;

namespace University.Models
{
  public class Student
  {
    public Student()
    {
      this.Courses = new HashSet<CourseStudent>();
    }

    public int StudentId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime Enrollment { get; set; }
    public ICollection<CourseStudent> Courses { get; }

  }
}

Models/UniversityContext.cs
using Microsoft.EntityFrameworkCore;

namespace University.Models
{
  public class UniversityContext : DbContext
  {
    public DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }

    public UniversityContext(DbContextOptions options) : base(options) { }
  }
}

Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using University.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace University.Controllers
{
  public class CoursesController : Controller
  {
    private readonly UniversityContext _db;

    public CoursesController(UniversityContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }


    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
          .Include(course => course.Students)
          .ThenInclude(join => join.Student)
          .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
      ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "FirstName LastName");
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course, int StudentId)
    {
      if (StudentId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { StudentId = StudentId, CourseId = course.CourseId });
      }
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddStudent(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
      ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "FirstName LastName");
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult AddStudent(Course course, int StudentId)
    {
      if (StudentId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { StudentId = StudentId, CourseId = course.CourseId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteStudent(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      _db.CourseStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace University.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using University.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace University.Controllers
{
  public class StudentsController : Controller
  {
    private readonly UniversityContext _db;

    public StudentsController(UniversityContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Student> model = _db.Students.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Title");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student, int CourseId)
    {
      _db.Students.Add(student);
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisStudent = _db.Students
        .Include(student => student.Courses)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Edit(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Title Number");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { StudentId = student.StudentId, CourseId = CourseId });
      }
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCourse(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Title");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult AddStudent(Student student, int CourseId)
    {
      if (CourseId != 0)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteCourse(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      _db.CourseStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

Views/Courses/AddStudent.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h2>Add a Student</h2>

<h4>Add a student to this course: @Html.DisplayFor(model => model.Title) @Html.DisplayFor(model => model.Number)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CourseId)

    @Html.Label("Select Student")
    @Html.DropDownList("StudentId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to Course List", "Index")</p>

Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h4>Add a new Course</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Title)
    @Html.TextBoxFor(model => model.Title)
    @Html.LabelFor(model => model.Number)
    @Html.TextBoxFor(model => model.Number)
    <input type="submit" value="Add new Course" />
}
<p>@Html.ActionLink("Show all Courses", "Index")</p>

Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h2>Are you sure you want to delete this course?</h2>

@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title) @Html.DisplayFor(model => model.Number) 
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Courses", "Index")

Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course;

<h2>Course Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title) @Html.DisplayFor(model => model.Number)</h3>

@if(@Model.Students.Count == 0)
{
  <p>There are no students enrolled in this course!</p>
}
else
{
  <h4>Students enrolled in this course:</h4>
  <ul>
  @foreach(var join in Model.Students)
  {
    <li>@join.Student.FirstName @join.Student.LastName</li>
  }
  </ul>
}

<p>@Html.ActionLink("Enroll Students", "AddStudent", new {id = Model.CourseId})</p>
<p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Back to Courses", "Index")</p>

Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Course

<h2>Edit</h2>

<h4>Edit this course: @Html.DisplayFor(model => model.Title) @Html.DisplayFor(model => model.Number)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CourseId)

    @Html.LabelFor(model => model.Title)
    @Html.EditorFor(model => model.Title)
    @Html.LabelFor(model => model.Number)
    @Html.EditorFor(model => model.Number)

    @Html.Label("Add Student")
    @Html.DropDownList("StudentId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Courses", "Index")</p>

Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using University.Models;
@model List<University.Models.Course>;

<h2>Courses</h2>

@if (@Model.Count == 0)
{
  <h3>No courses have been added yet!</h3>
} 

@foreach (Course course in Model)
{
  <li>@Html.ActionLink($"{course.Title} {course.Number}", "Details", new { id = course.CourseId })</li>
}

<p>@Html.ActionLink("Add new Course", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h2>Welcome to the Registrar's Office!</h2>
<p>@Html.ActionLink("See all Courses", "Index", "Courses")</p>
<p>@Html.ActionLink("See all Students", "Index", "Students")</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h2>Add a Course</h2>

<h4>Add a Course for this Student: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.Label("Select Course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h4>Add a new Student</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.FirstName)
    @Html.TextBoxFor(model => model.FirstName)
    @Html.LabelFor(model => model.LastName)
    @Html.TextBoxFor(model => model.LastName)
    @Html.LabelFor(model => model.Enrollment)
    @Html.TextBoxFor(model => model.Enrollment, "{0:yyyy-MM-dd}", new { type="date" })
    @Html.Label("Add Course")
    @Html.DropDownList("CourseId")
    
    <input type="submit" value="Add new Student" />
}
<p>@Html.ActionLink("Show all Students", "Index")</p>

Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h2>Are you sure you want to delete this student?</h2>

<h3>Student Name: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h3>  
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Students", "Index")

Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student;

<h2>Student Details</h2>
<hr />
<h3>Name: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h3>

@if(@Model.Courses.Count == 0)
{
  <p>This student is not enrolled in any courses!</p>
}
else
{
  <h4>Course enrollment:</h4>
  <ul>
  @foreach(var join in Model.Courses)
  {
    <li>@join.Course.Title @join.Course.Number</li>
  }
  </ul>
}

<p>@Html.ActionLink("Add a Course", "AddCourse", new {id = Model.StudentId})</p>
<p>@Html.ActionLink("Edit Student", "Edit", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Delete Student", "Delete", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Back to Students", "Index")</p>

Views/Students/Edit.cshtml
@{
  Layout = "_Layout";
}

@model University.Models.Student

<h2>Edit</h2>

<h4>Edit this student: @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StudentId)

    @Html.LabelFor(model => model.FirstName)
    @Html.EditorFor(model => model.FirstName)
    @Html.LabelFor(model => model.LastName)
    @Html.EditorFor(model => model.LastName)
    @Html.LabelFor(model => model.Enrollment)
    @Html.EditorFor(model => model.Enrollment, "{0:yyyy-MM-dd}", new { type="date" })
    
    @Html.Label("Add Course")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to Students", "Index")</p>

Views/Students/Index.cshtml
@{
  Layout = "_Layout";
}

@using University.Models;
@using System.Security.Claims
@model IEnumerable<University.Models.Student>

<h1>Students for @User.Identity.Name</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Student student in Model)
    {
      <li>@Html.ActionLink($"{student.FirstName} {student.LastName}", "Details", new { id = student.StudentId })</li>
    }
  </ul>
} 
else
{
  <h3>No students have been added yet!</h3>
}

<p>@Html.ActionLink("Add new student", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>